#!/bin/sh

cd /opt/political-feed/

PATH="/opt/political-feed/:$PATH"

fetch

today="$(date +'%Y-%m-%d')"
for word in Internet Telekommunikationsüberwachung TKÜ Überwachung Funkzellenabfrage Vorratsdatenspeicherung Bestandsdatenauskunft PNR Fluggastdaten TKG Telekommunikationsgesetz "Open Data" Transparenzgesetz Informationsfreiheitsgesetz Urheberrecht Netzpolitik Datenschutzgrundverordnung Beschäftigtendatenschutz Videoüberwachung Drohnen Terrorismus Netzneutralität Familienpolitik Zwangseinweisung "psychologische Begutachtung" Tierschutz Massentransporte Justizpolitik Hoheitsrechte Richter Staatsanwälte Staatsanwalt Vetternwirtschaft Lobby; do
	reportWord "$word"

	for fmt in html rss; do
		cp "data/$today/report/$word.$fmt" "/var/www/report/$today-$word.$fmt"
		chmod o+r "/var/www/report/$today-$word.$fmt"
		ln -sf "/var/www/report/$today-$word.$fmt" "/var/www/report/$word.$fmt"
	done
done
